server:
  error:
    whitelabel:
      enabled: false

spring:

  mvc:
    throw-exception-if-no-handler-found: true

  jpa:
    open-in-view: false

  datasource:
    pg:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5445/postgres?stringtype=unspecified
      username: postgres
      password: password

  mongodb:
    host: localhost
    port: 27017
    username: root
    password: 1234
    auth-database: admin